### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by NikitaIT** [greggman/threejsfundamentals#16]
en
There is no check for the length of the array, but this is not the root of the problem.
https://github.com/greggman/threejsfundamentals/blob/9a02836a7f334d24f7d3c8cefc94e9297316e931/build/js/build.js#L453

As a developer, you cannot keep up with changes in duplicate code.
- It is necessary to lay out the general infrastructure of projects in a separate repository, it saved a lot of time.

> ru sourse
> Нет проверки длинны массива, но это не корень проблемы.
> https://github.com/greggman/threejsfundamentals/blob/9a02836a7f334d24f7d3c8cefc94e9297316e931/build/js/build.js#L453
> 
> Как разработчик, вы не можете уследить за изменениями в дублируемом коде.
> - Нужно вынести общую для проектов инфраструктуру в отдельный репозиторий, это сэкономит много времени.

**Comment by NikitaIT** [comment]
@greggman 
articles[0].dateModified <- if you add only index.md and toc in new translation, then the articles length = 0

this is fixed in webgl fundamentals build.js

**Comment by greggman** [comment]
Uploaded a new one. try again?

**Comment by NikitaIT** [comment]
Ok, but putting the infrastructure into a separate repository would be the best solution)
